# Generated by Django 3.0.5 on 2021-12-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toppings',
            old_name='types',
            new_name='name',
        ),
        migrations.AddField(
            model_name='toppings',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Pizza'),
            preserve_default=False,
        ),
    ]
